export const EVENT_NAME_CHANGED = 'EVENT_NAME_CHANGED';
export const AMOUNT_PEOPLE_CHANGED = 'AMOUNT_PEOPLE_CHANGED';
export const READY_TO_START = 'READY_TO_START';
export const ADD_ITEM = 'ADD_ITEM';
export const GO_BACK = 'GO_BACK';